version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - mynetwork
  
  flask_app:
    build: ../apps/flask_api
    ports:
      - "5000:5000"
    volumes:
      - ../apps/flask_api:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb"
    networks:
      - mynetwork
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python3.9 app.py"
  
  next_app:
    build: ../apps/wind-turbine
    ports:
      - "3000:3000"
    volumes:
      - ../apps/wind-turbine:/app
    depends_on:
      - flask_app
    networks:
      - mynetwork
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb"
    command: /bin/sh -c "npm install --legacy-peer-deps && npm install @mui/material @emotion/react @emotion/styled --force && npm i @mui/icons-material --force && npm install next-transpile-modules && ./wait-for-it.sh flask_app 5000 &&  npm run dev"

networks:
  mynetwork:
